### ISSUE TITLE
Dark mode not functioning as expected. 

### ISSUE THREAD

**Issue by pranay-simejia** [ALPHAVIO/BlogSite#106]
### **Describe the bug**
When dark mode is enabled, on loading a new route dark mode gets disabled.

### **To Reproduce**
1. Go to ''https://blogsite321.herokuapp.com/"
2. Click on 'dark mode button'
3. click on home tab
4. See switched to light mode.

### **Expected behavior**
Dark mode should persist on switching routes.

**Comment by Pranav016** [comment]
This is happening because we are not logging in, there is no session to save your current details. We'll work on a sign-up and log-in system and then we'll be able to store your current state of the website. Right now every time you open a new route, it renders like you just opened the website. Hope this clears your doubt, this is one feature that will come soon. I am closing this issue for now, re-open the issue if any other query.
