### ISSUE TITLE
Add login system for writers and readers.

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/BlogSite#108]
### Feature request
Add a login system for writers and readers. Both will have separate privileges, only writers will be able to delete their own blogs. Readers cannot delete any blogs, they can only read or comment.

To sum this up, add a sign up and login system and allow only writers to delete their own blogs. 

### Describe the solution you'd like
You can passport js for authentication and login. A few new parameters need to be added to the blog schema like who wrote the article so that option only appears to them for deleting that article.

### Describe how this feature will be useful to our readers.
No outside person/ reader can delete the blogs.

**Comment by Pranav016** [comment]
Discuss with me about this issue in the comments here before working on it. Discuss your plan of action and your schema for the DB.

**Comment by Subhra264** [comment]
The schema for user --- It will have  a username, an email, password, posts,  first name, last name etc. for the basic.  Followers, followings and other schema properties could also be added  as new features so that users can follow others.

For authentication -- JWT(jsonwebtoken module) or passport.js( passport-jwt ) any thing can be used.  Though I am much more familiar with jsonwebtoken module. When the user successfully logs in , a json-web-token will be given to the user and whenever the user will make some requests to the protected routes, the server will check if the user has a valid token or not, if he/she has one, then only the user will have access to the private routes, otherwise they will be redirected to the log in page.

**Comment by Pranav016** [comment]
Let's not add the follow functionality right now, for that you can raise another issue after this. Schema looks fine, we can discuss if any other additions required. You can work on this issue 👍 

Let me know which open-source program are you working on this for? JWoC right? I'll add appropriate labels

**Comment by Subhra264** [comment]
Yes jwoc
