### ISSUE TITLE
Fix the footer

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/BlogSite#162]
### Is your feature request related to a problem? Please describe.
Footer positioning and info not correct.

### Describe the solution you'd like
Make the footer stick at the bottom for every page. Update the email in the footer to one on the contact page.

![image](https://user-images.githubusercontent.com/54665036/107808019-fc438880-6d8e-11eb-8e6e-a1a4cdd50e03.png)

**Comment by Ankita297** [comment]
I would like to work on this issue  .

**Comment by Pranav016** [comment]
> I would like to work on this issue .

Will you be working under JWoC or Mexili ?

**Comment by Abhijay007** [comment]
@Pranav016 sir I already solved it, but I forget to ping message for the assignment because I am a bit busy 😅.

![about us](https://user-images.githubusercontent.com/64387054/107855342-aed72200-6e47-11eb-8666-e5620ff7c593.PNG)
![contact us](https://user-images.githubusercontent.com/64387054/107855344-b0084f00-6e47-11eb-8268-97a8a9657f73.PNG)

but as you assigned this issue to @Ankita297 let her work on it.

PS: I will make open a PR for this if she is not able to find the solution.

@Ankita297 if you need any help with this issue you can ask!!

**Comment by Pranav016** [comment]
> @Pranav016 sir I already solved it, but I forget to ping message for the assignment because I am a bit busy 😅.
> 
> ![about us](https://user-images.githubusercontent.com/64387054/107855342-aed72200-6e47-11eb-8666-e5620ff7c593.PNG)
> ![contact us](https://user-images.githubusercontent.com/64387054/107855344-b0084f00-6e47-11eb-8268-97a8a9657f73.PNG)
> 
> but as you assigned this issue to @Ankita297 let her work on it.
> 
> @Ankita297 if you need any help with this issue you can ask!!

Good work, but make sure to get the issue assigned before you start working on it..

**Comment by Ankita297** [comment]
Sir please review  my PR

**Comment by Pranav016** [comment]
> > I would like to work on this issue .
> 
> @Ankita297 Which program do you want to work under? I'll add the appropriate labels

@Ankita297
