### ISSUE TITLE
Add a GitHub action to auto-assign Mentors for every PR

### ISSUE THREAD

**Issue by m-code12** [ALPHAVIO/BlogSite#204]
I would like to add a GitHub action to auto-assign mentors for every PR. It sometimes becomes hectic for the mentors to take a look at all the Projects for the PRs made by the Contributors. This action would give a nice notification about reviewing the pr and make things pretty easy for the mentor. It would automatically ask for reviews by the mentors on every pr created.

Demo :
<img src="https://user-images.githubusercontent.com/1641039/78471193-71573200-776a-11ea-9b40-810c2d63270e.png">

**Comment by m-code12** [comment]
@Pranav016 Can I implement this?

**Comment by Pranav016** [comment]
I feel like I would be assigned every time a new PR is made. Since for GSSoC we'll be onboarding new mentors and even new org members so it doesn't make sense right now since I am the only one right now. This can be useful and can be added sometime in the future. 

Closing the issue for now, re-open if required.
