### ISSUE TITLE
Making the site responsive 

### ISSUE THREAD

**Issue by riddhisiddarkar** [ALPHAVIO/BlogSite#251]
Making changes to the existant code to make it mobile friendly

**Comment by tejasimangale** [comment]
I would like to work on this issue as a participant of gssoc21

**Comment by RushanKhan1** [comment]
Hey guys! This issue is very similar to Issue #248 opened 4 hours ago and that issue has already been self-assigned therefore I request you guys to find or create a different issue to work with! And as a quick reminder, I would suggest you to please check for previous similar issues before creating a new one as stated in the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md).

**Comment by tejasimangale** [comment]
Ohk @RushanKhan1 Will take a note of this. Thank you!
