### ISSUE TITLE
Adding Express Validators

### ISSUE THREAD

**Issue by mani9896** [ALPHAVIO/BlogSite#332]
### Please assign me this task , as a part of GSSOC 21

```

**Comment by mani9896** [comment]
Hey I wanted to work on that issue, but got assigned to someone else

**Comment by RushanKhan1** [comment]
@mani9896 I have assigned you the issue since you wanted to work with it first and you are the author of the issue. Also, you are allowed to assign yourself if you are the author of the issue or the issue is free as stated in the [issue guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/.github/ISSUE_TEMPLATE/feature_request.md). You just need to comment ``/assign`` under the issue.

**Comment by RushanKhan1** [comment]
@aliya-rahmani I am sorry for unassigning you from the issue, I hope you understand why I did that. Please find a different issue to work with or create a non-duplicate new one.

**Comment by aliya-rahmani** [comment]
@RushanKhan1 Sure, no problem!

**Comment by RushanKhan1** [comment]
@mani9896 Hey, did you pull the new changes, and are you working on this issue with the updated code?

**Comment by mani9896** [comment]
@RushanKhan1 yes I have and I am working
